sudo: false
language: java
jdk:
- oraclejdk7

notifications:
  email:
    recipients:
    - ldp4j-commits@googlegroups.com
    on_success: always
    on_failure: always

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar"

before_cache:
  - source ./.travis/utils.sh backup-maven-repo

before_install:
  - source ./.travis/utils.sh prepare-build-bom $ENCRYPTION_PASSWORD

install:
  - "/bin/true"

script:
  - source ./.travis/build.sh

after_success:
  - source ./.travis/utils.sh restore-maven-repo
  - source ./.travis/qa.sh

env:
  global:
  - secure: AAVZNDVtE0dgPK7qZacSe6CUP0rGQG1SWQEzo8e0BH3WhJGFhM4vNQTR6N6KzjgUHmstfEM7nOdIcTSpHd+RFCKhDbZYl7iN1ZYUG/sn9KGbjyDWkC3EAddP4LZ9yDqQ1iYg5tQh59XC/Dne/peXOJRAf+RocjuhvGXsC3rT0/c=
  - secure: e/sKP9FhN2qVMWmME2BF1XubJxJ7gT+gQq7/LlihSGCrRHurnwPKf3rGDZqjx4Y9mjKsB6N/a7t7m4cGsoW8/p8OMgFLZw96b2E9GkNvbUs4m7SsUBk5KaNVapNc+TtDsM+0Dn34Nq/hlo+rDvgVPGSM7uxe1eGixlDkbbrrmKQ=
  - secure: JSJjWCP9wpjULEIg4dLSilok1n89aJaMIKun3dXr/qlAtdW9n+/TmoOnXzBYWS4tJ4qP5bKaXcwxCPz9Cl4xmZmLzjVEgHM8KXOEqySCNFsz0zIktmQ8bTbcDS+QVM6iWzGV3tvj6GV5PAuh8KuAY2Tr8Ibis2nGBcWl3DZLFvA=
  - secure: c1uoP8L8mbF+LpYHmWlu35VRIRu85iTct36g1CDG/t/ydZsRFWtsYvjOuRvjOshTpYu+pz4Cw40RZCMrW+N1UvnMZGyGH89SKeI3dheSWe5yLVGghTCZ/ukjNEQgp91qrHgDZ0q901vOAceOAMxSi2avek4I1RV8OV+ii4NUPsc=
  - secure: Bi7yi88eEbNRVExQmt8dkgN0Vrc1QCI9Mwh0O3+Y0XQ2Fn6+i6ck4Ec19Yn/UzRhsyZrK8zS6q12TKxjcsIdIRwwx9U9QobifWosU+J0ZaAjYfWfvXOHsESYEp10PXwKNs9mLlZlq4T1hq9YDkabKSUw9xroUM4JwLjABkelJ0I=
  - secure: dXCSXC93q0C2sVzIXFT3NyJuDeIW7HWTYk1YdOeu/E8wDj8iP6vuU+tFgbQx5iop+wnLo6OGU1ZxQ4M1tUmJKXeSG4+5zrBnhOvG8nT6CFYBUeqfWn7B8U4VEJ8j384ipCN76c3nMas7OPeEPOCiOBJdA5T0T1TGHNpcjGcgzkU=
  - secure: b/uwCctNVibGpYG7bsrWuq6kGJMXP8MXknRiE7q070XDnkcvlaqTnQOetoyaVfAUl/ApDLaaEm2m0OEx0sDRzGAmNBl9R/bYO/aJ6+9wulKOLsQ17KYOmbRT/+4Css5OMN0I8IuaaUOdPuGgf+Hf6gvnCqJwv5VXI5zmsIYnzxI=
  - secure: EB3zC7/o6uvZOh/lyg6xqvpYNpBBMYv8mt/4AdsCx/M6WpjtXhLSMzbazkTgF0CIPcedFg1ERoMaZOtTBe7QlVXzu8HSU2g1lx3ibzMMecKrttO2/wnK/n7QsuvkcxzYkJy9tygawl1Gh8/3RXleQrO1CgTYXfL32mqCbDDRBfk=
  - secure: dE+6U8VeZuB8NLQCjcG3xrc/KDUwZA9Br9UHbJ/ishMut0BlylnXf3CzW7AOHsHRAf5n7nsc+pI+qNA0dP/CUBniWMJVxu88l6CAgGlZ2XfBb2HCXhtsV72SjVatYC4D6l8LbzYWQG3PCUA1GHmT1r3KHSi+Il2Avz34i3rzxgM=
